package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"

	"github.com/alexduzi/orderscleanarch/internal/entity"
	"github.com/alexduzi/orderscleanarch/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input usecase.OrderInputDTO) (*entity.Order, error) {
	output, err := r.CreateOrderUseCase.Execute(input)
	if err != nil {
		return nil, err
	}

	return &entity.Order{
		ID:         output.ID,
		Price:      output.Price,
		Tax:        output.Tax,
		FinalPrice: output.FinalPrice,
	}, nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*entity.Order, error) {
	orders, err := r.ListOrderUseCase.Execute()
	if err != nil {
		return nil, err
	}

	result := make([]*entity.Order, 0, len(orders))
	for _, o := range orders {
		result = append(result, &entity.Order{
			ID:         o.ID,
			Price:      o.Price,
			Tax:        o.Tax,
			FinalPrice: o.FinalPrice,
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
